### ISSUE TITLE
npm install fail because  '@strictd/ng2-modal' is not in the npm registry

### ISSUE THREAD

**Issue by giantray** [strictd/angular2-ionic2-webpack#2]
after I clone the repo,I try to exec "npm install",but I get fail.the command windows show that:

npm ERR! 404 Not found : @strictd/ng2-modal
npm ERR! 404
npm ERR! 404  '@strictd/ng2-modal' is not in the npm registry.

I search on the https://www.npmjs.com. And there is no "@strictd/ng2-modal" on it

**Comment by jose2007kj** [comment]
me too having same error.....

**Comment by jose2007kj** [comment]
@Giantray solved this issue by adding path to the repository inside dependencies in package.json file  
```
"@strictd/ng2-madame": "https://github.com/strictd/ng2-madame",
    "@strictd/ng2-modal": "https://github.com/strictd/ng2-modal",    
    "@strictd/ng2-set-focus": "https://github.com/strictd/ng2-set-focus",

```
ie. i replaced following lines in dependencies of package.json file 
```
"@strictd/ng2-madame": "^1.1.4",
    "@strictd/ng2-modal": "^0.0.24",    
    "@strictd/ng2-set-focus": "^1.1.3",

```

**Comment by strictd** [comment]
Hey! sorry I didn't have a watcher turned on this repo. The npm module ng2-modal was still set to private.. this has been fixed.

I also made huge version bumps and got more in sync with the https://github.com/preboot/angular2-webpack repo.

I'm going to close this, let me know if you still have trouble grabbing any npm modules.
