### ISSUE TITLE
TypeError: Knex.on is not a function

### ISSUE THREAD

**Issue by jose2007kj** [strictd/angular2-ionic2-webpack#3]
![capture](https://cloud.githubusercontent.com/assets/10298207/20897829/f6f60296-bb49-11e6-972f-8a23b136f65a.PNG)

sir.......i am getting the following error when trying to do node server.js  , where i might be going wrong?

**Comment by strictd** [comment]
it maybe the version of knex. I recently did a huge commit bump to the entire repo. Been working on other projects I forgot about this repo and wasn't on the watch list. Let me know if you're still having the issue after pulling the latest commits.

**Comment by jose2007kj** [comment]
OK.....SIR......THANKS.............................. I WILL LET U KNOW IF I GET AGAIN
